services:
  app:
    build: .
    restart: always
    container_name: app
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/javacodetest
      - JDBC_USER=javacodetestuser
      - JDBC_PASSWORD=password
      - SPRING_DATASOURCE_TOMCAT_MAX_ACTIVE=80
      - SPRING_DATASOURCE_TOMCAT_MAX_IDLE=30
      - JAVACODETEST_LOGGING_LEVEL=INFO
    ports:
      - 8080:8080
    volumes:
      - ./src/main/resources/logback.xml:/usr/local/tomcat/webapps/javacodetest/WEB-INF/classes/logback.xml
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: javacodetestuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: javacodetest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
